#!/bin/bash
bump2version --list --commit --tag patch locast2dvr/__init__.py && \
git push && git push --tags && \
rm -rf dist build  && python setup.py sdist bdist_wheel && python -m twine upload dist/*


